CREATE TABLE IF NOT EXISTS withdrawals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_email VARCHAR(190) NOT NULL,
  wallet_provider VARCHAR(100) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('EN_PROCESO','PAGADO','RECHAZADO') NOT NULL DEFAULT 'EN_PROCESO',
  proof_json TEXT NULL,
  created_at DATETIME NOT NULL
);

